[TShutdown]
Shutdown_FontName=MS Sans Serif
Shutdown_FontSize=8
Shutdown_FontCharset=1
suiForm1_Caption=Shutdown Monster
Time_Caption=Genaue Zeit
Set1_Caption=Setzen
Canc1_Caption=Abbrechen
Button2_Caption=This ain't here
CountDown_Caption=Countdown
Set2_Caption=Setzen
Canc2_Caption=Abbrechen
IPing_Caption=Datei
infoPing_Caption=Wenn diese Datei verschwindet wird, wird der PC heruntergefahren.
infoCheck_Caption=Überprüfe alle
Set3_Caption=Setzen
Canc3_Caption=Abbrechen
AltOptions_Caption=Fortgeschrittene Optionen
GB_Design_Caption=Design
auto_Caption=Jeden Tag
parentalcontrol_Caption=Elternkontrolle
aftertime_Caption=Nach der Zeit (sehr gemein!)
auto2_Caption=Beim Systemstart mitstarten
minimCB_Caption=Beim Start minimieren
ontopCB_Caption=Immer im Vordergrund
GB_Shutdown_Caption=Herunterfahren
force_Caption=Zwinge Anwendungen zum Schließen
defcommand_Items[0]=Strom aus
defcommand_Items[1]=Herunterfahren
defcommand_Items[2]=Neu Starten
defcommand_Items[3]=Abmelden
defcommand_Items[4]=Standby
defcommand_Items[5]=Hibernate
defcommand_Items[6]=Arbeitsplatz sperren
defcommand_Items[7]=Bildschirmschoner
defcommand_Items[8]=Alarm
defcommand_Items[9]=CD auswerfen
defcommand_Items[10]=Schublade schließen
defcommand_Items[11]=Papierkorb leeren
defcommand_Items[12]=Zwischenablage leeren
defcommand_Items[13]=Monitor aus
defcommand_Items[14]=Monitor ein
defcommand_Items[15]=Temporäre Internetdateien löschen
wake_CB_Caption=Disable wake events
GB_Alarm_Caption=Alarm
GB_Before_Caption=Vor dem Herunterfahren machen
beshutCB_Caption=Starte dieses Programm vor dem Herunterfahren
logCB_Caption=Loggen
annCB_Caption=Countdown vor dem Herunterfahren
GB_Other_Caption=Andere Optionen
server_CB_Caption=Server Modus aktivieren
Button1_Caption=Nach Updates suchen
Veszhelyzet_Caption=Schnellzugriff
PowerOff_Caption=&Strom aus
ReBoot_Caption=&Neustart
LogOff_Caption=&Abmelden
ShutDown_Caption=&Herunterfahren
Hibernate_Caption=&Hibernate
LockWS_Caption=Arbeitsplatz sperren
SDMenu_Caption=Beenden-Menü
SSOn_Caption=Bildschirmschoner
BitBtn1_Caption=&Alarm
eject_Caption=CD auswerfen
close_Caption=Schublade schließen
recbin_Caption=Papierkorb leeren
clipb_Caption=Zwischenablage leeren
mon0_Caption=Monitor aus
mon1_Caption=Monitor ein
BitBtn2_Caption=Temporäre Internetdateien löschen
Suspend_Caption=&Standby
UserSpecific_Caption=Benutzerabhängig
UserCB_Caption=Aktivieren
TabSheet2_Caption=Atomuhr
atom_label_Caption=Die Systemzeit ist nicht synchronisiert
atom_do_Caption=Synchronisieren
atom_CB_Caption=Beim Programmstart überprüfen
Shutdown_Hint=Shutdown Monster
Valasztas_Hint=Wähle einen Reiter!
Time_Hint=Hier kannst du eine genaue Zeit einstellen
logo_Hint=About
Set1_Hint=Aktivieren
Canc1_Hint=Stopp
Save1_Hint=Speichern
Calendar_Hint=Hier kannst du das Datum einstellen
Idopont_Hint=Hier kannst du die Zeit einstellen
CountDown_Hint=Hier kannst du den Countdown einstellen
Most_Hint=Hier kannst du die verbleibende Zeit in Prozent sehen
Set2_Hint=Aktivieren
Canc2_Hint=Stopp
Save2_Hint=Speichern
CD1_Hint=Uhr
CD2_Hint=Minute
CD3_Hint=Sekunde
IPing_Hint=Hier kannst du eine Datei festlegen, die überprüft wird
infoPing_Hint=Wenn diese Datei verschwindet wird, wird der PC heruntergefahren
infoCheck_Hint=Überprüfe alle x Minuten
PingTime_Hint=Hier kannst du die Zeit zwischen den einzelnen Überprüfungen einstellen
Set3_Hint=Aktivieren
Save3_Hint=Speichern
Canc3_Hint=Stopp
eleres_Hint=Hier kannst du den Namen der Datei angeben
AltOptions_Hint=Hier kannst du weitere Optionen einstellen
auto_Hint=Der Computer wird jeden Tag zur exakten Zeit herunterfahren oder wenn der Countdown abgelaufen ist
parentalcontrol_Hint=Du kannst das Programm nur mit Strg+Alt+Entf beenden ('Stiller Modus')
aftertime_Hint=Wenn du den Rechner nach der angegebenen Zeit anschaltest, fährt er automatisch runter
spintime_Hint=Hier kannst du einstellen, wie viele Sekunden vor dem Herunterfahren gewartet werden soll
auto2_Hint=Das Programm kann bei jedem Systemstart geladen werden
minimCB_Hint=Beim Start minimieren
force_Hint=Zwingt alle Anwendungen zum Schließen, auch wenn es ungespeicherte Dokumente gibt
defcommand_Hint=Hier kannst du den Standardbefehl festlegen
wake_CB_Hint=Disables all wake events (Stand By and Hibernate)
wavE_Hint=Hier kannst du die zu spielende Datei einstellen
wavSE_Hint=Hier kannst du einstellen, wie oft die Datei abgespielt werden soll
beshutCB_Hint=Starte dieses Programm vor dem Herunterfahren
beshutE_Hint=Hier kannst du die Datei festlegen, die vor dem Herunterfahren ausgeführt werden soll
logCB_Hint=Herunterfahr-Vorgänge mitloggen
annCB_Hint=Visueller und akustischer Countdown 9 Sekunden vor dem Herunterfahren
Save4_2_Hint=Speichern
server_CB_Hint=Du kannst deinen Computer über das Internet ausschalten
Veszhelyzet_Hint=Hier kannst du Tastaturkürzel einstellen oder den Computer schnell herunterfahren lassen
SpeedButton1_Hint=Effektuieren
PowerOff_Hint=Schaltet den PC aus (ATX benötigt)
ReBoot_Hint=Startet den PC neu
LogOff_Hint=Meldet den aktuellen Benutzer ab
Hibernate_Hint=Saves your current desktop state to your hard disk so that you can resume where you left off, then shuts down your computer.
HotKeyPOff_Hint=Strom aus
HotKeySD_Hint=Herunterfahren
HotKeyReB_Hint=Neustart
HotKeyLO_Hint=Abmelden
HotKeyHib_Hint=Hibernate
Save4_Hint=Speichern
LockWS_Hint=Sperrt den Arbeitsplatz
HotKeyLWS_Hint=Arbeitsplatz sperren
SDMenu_Hint=Zeige das Beenden-Menü von Windows
SSOn_Hint=Aktiviert den Bildschirmschoner
HotKeySS_Hint=Bildschirmschoner
BitBtn1_Hint=Sound spielen
HotKeyAA_Hint=Alarm
eject_Hint=Schublade öffnen
close_Hint=Schublade schließen
recbin_Hint=Papierkorb leeren
clipb_Hint=Zwischenablage leeren
HotKey1_Hint=CD auswerfen
HotKey2_Hint=Schublade schließen
HotKey3_Hint=Papierkorb leeren
HotKey4_Hint=Zwischenablage leeren
mon0_Hint=Monitor ausschalten
mon1_Hint=Monitor einschalten
hkmon0_Hint=Monitor aus
hkmon1_Hint=Monitor ein
BitBtn2_Hint=Temporäre Internetdateien löschen
hkctif_Hint=Temporäre Internetdateien löschen
Suspend_Hint=Puts your computer in a low-power state so that you can quickly resume your Windows session.
HotKeySus_Hint=Stand By
UserSpecific_Hint=Wenn sich er Benutzer abmeldet, verbiete ihm/ihr das Anmelden für einige Zeit
UserCB_Hint=Wenn sich er Benutzer abmeldet, verbiete ihm/ihr das Anmelden für einige Zeit
FromTime_Hint=Anfangszeit
ToTime_Hint=Endzeit
atom_do_Hint=Zeit synchronisieren
TrayIcon_Hint=Shutdown Monster
eleres_Filter=Alle Dateien (*.*)|*.*|Ausführbare Dateien (*.bat; *.com; *.exe)|*.bat;*.com;*.exe
wavE_Filter=Töne (*.wav)|*.wav|Alle Dateien(*.*)|*.*
beshutE_Filter=Ausführbare Dateien (*.bat; *.com; *.exe)|*.bat;*.com;*.exe|Alle Dateien (*.*)|*.*
ShutDown_B_Caption=&Herunterfahren
ShutDown_B_Hint=Fährt das PC herunter
TrayIcon_Hint=Shutdown Monster
Kikapcsols1_Caption=&Strom aus
N15percmlva1_Caption=Nach &15 Minuten
N30percmlva1_Caption=Nach &30 Minuten
N60percmlva1_Caption=Nach &60 Minuten
N120percmlva1_Caption=Nach 1&20 Minuten
Most1_Caption=&Jetzt
Lellts1_Caption=&Herunterfahren
jraindts1_Caption=&Neu starten
Kijelentkezs1_Caption=&Abmelden
hibernls1_Caption=&Standby
Munkallomszrolsa1_Caption=&Arbeitsplatz sperren
Kpernyvd1_Caption=Bildschirmschoner
Ments1_Caption=Speiche&rn
Mgsem1_Caption=&Abbrechen
Kilps1_Caption=&Beenden
Delet1_Caption=Entfernen
Kapcs_Caption=Verbindung
Disconnect_Caption=Verbindung trennen
Connect_Caption=Verbinden
IP_Edit_Hint=Gib die IP-Adresse des Clients ein!
langCB_Hint=Hier kannst du die Standardsprache festlegen
TabSheet1_Caption=CPU Benutzung
Label1_Caption=Aktuell CPU Benutzung:
CPU_L_Caption=100%
If_below_Caption=Herunterfahren wenn die Benutzung des CPUs bleibt unter 
If_stays_Caption=% für
If_then_Caption=Minuten
CPU_SE_Hint=%
Canc4_Caption=Abbrechen
Canc4_Hint=Stopp
Set4_Caption=Setzen
Set4_Hint=Aktivieren
SaveHK_Hint=Speichern
Hook_CB_Caption=Herunterfahren nur wenn keine Dateneingabe gibt
volfade_CB_Caption=Lautstärke abblenden vor dem Herunterfahren
Label1_Hint=Zeight die Benutzung des CPUs
CPUMin_SE_Hint=Minuten
Hook_CB_Hint=Herunterfahren nur wenn das Maus nicht bewegt und das Keyboard ist nicht benutzt
ontopCB_Hint=Immer im Vordergrund
volfade_CB_Hint=Lautstärke abblenden vor dem Herunterfahren
volfade_E_Hint=Geschwindigkeit der Abblendung
Button1_Hint=Nach Updates suchen
atom_add_Hint=Server zugeben
Update_L_Caption=There are no new updates available!
Update_L_Hint=Homepage des Programs besuchen
