[TShutdown]
Shutdown_FontName=MS Sans Serif
Shutdown_FontSize=8
Shutdown_FontCharset=1
suiForm1_Caption=Shutdown Monster
Time_Caption=Exact time
Set1_Caption=Set
Canc1_Caption=Cancel
Button2_Caption=This ain't here
CountDown_Caption=Countdown
Set2_Caption=Set
Canc2_Caption=Cancel
IPing_Caption=File
infoPing_Caption=If this file disappears, your PC will turn off
infoCheck_Caption=Check every
Set3_Caption=Set
Canc3_Caption=Cancel
AltOptions_Caption=Advanced
GB_Design_Caption=Design
auto_Caption=Every day
parentalcontrol_Caption=Parental control
aftertime_Caption=After time (use at your own risk)
auto2_Caption=Start on system launch
minimCB_Caption=Run minimized
ontopCB_Caption=Stay always on top
GB_Shutdown_Caption=Shutdown
force_Caption=Force applications to quit
defcommand_Items[0]=Power Off
defcommand_Items[1]=Shutdown
defcommand_Items[2]=Restart
defcommand_Items[3]=Log Off
defcommand_Items[4]=Stand By
defcommand_Items[5]=Hibernate
defcommand_Items[6]=Lock Workstation
defcommand_Items[7]=Screensaver
defcommand_Items[8]=Alarm
defcommand_Items[9]=Eject CD
defcommand_Items[10]=Close tray
defcommand_Items[11]=Empty Recycle Bin
defcommand_Items[12]=Clear Clipboard
defcommand_Items[13]=Monitor off
defcommand_Items[14]=Monitor on
defcommand_Items[15]=Clear Temporary Internet Files
wake_CB_Caption=Disable wake events
GB_Alarm_Caption=Alarm
GB_Before_Caption=Do before shutdown
beshutCB_Caption=Start this program before shutdown
logCB_Caption=Logging
annCB_Caption=Countdown before shutdown
GB_Other_Caption=Other
server_CB_Caption=Enable server mode
Button1_Caption=Check for Updates
Veszhelyzet_Caption=Fast access
PowerOff_Caption=T&urn Off
ReBoot_Caption=&Restart
LogOff_Caption=&Log OFf
ShutDown_Caption=Shut&down
Hibernate_Caption=&Hibernate
LockWS_Caption=Lock &Workstation
SDMenu_Caption=Shutdown &Menu
SSOn_Caption=Scree&nsaver
BitBtn1_Caption=&Alarm
eject_Caption=Eject CD
close_Caption=Close tray
recbin_Caption=Empty Recycle Bin
clipb_Caption=Clear Clipboard
mon0_Caption=Monitor off
mon1_Caption=Monitor on
BitBtn2_Caption=Clear Temporary Internet Files
Suspend_Caption=&Stand By
UserSpecific_Caption=User specific
UserCB_Caption=Enable
TabSheet2_Caption=Atomic clock
atom_label_Caption=The system time is not synchronized
atom_do_Caption=Synchronize
atom_CB_Caption=Check on program start
Shutdown_Hint=Shutdown Monster
Valasztas_Hint=Choose a tab!
Time_Hint=You can set an exact time here
logo_Hint=About
Set1_Hint=Activate
Canc1_Hint=Stop
Save1_Hint=Save
Calendar_Hint=You can set the date here
Idopont_Hint=You can set the time here
CountDown_Hint=You can set the countdown here
Most_Hint=Here you can see the remaining percentage of the time
Set2_Hint=Activate
Canc2_Hint=Stop
Save2_Hint=Save
CD1_Hint=Hour
CD2_Hint=Minute
CD3_Hint=Second
IPing_Hint=You can set a file to check here
infoPing_Hint=If this file disappears, your PC will turn off
infoCheck_Hint=Check every given minutes
PingTime_Hint=Here you can set how long to wait before the checkings
Set3_Hint=Activate
Save3_Hint=Save
Canc3_Hint=Cancel
eleres_Hint=You can type in the name of the file here
AltOptions_Hint=You can set more advanced options here
auto_Hint=The computer will shut down every day either if the countdown is over or at the exact time
parentalcontrol_Hint=You can close the program only with Ctrl-Alt-Del ('Silent Mode')
aftertime_Hint=If you turn on the computer after the given time, it automatically shuts down
spintime_Hint=Here you can set, how many seconds to wait before the shutdown
auto2_Hint=The program can automatically start at system launches
minimCB_Hint=The program will automatically get minimized
force_Hint=Forces all applications to quit, even if there are unsaved documents
defcommand_Hint=You can set the default command here
wake_CB_Hint=Disables all wake events (Stand By and Hibernate)
wavE_Hint=Here you can set, which sound to play
wavSE_Hint=Here you can set, how often to repeat the sound
beshutCB_Hint=Launch this program before shutdown
beshutE_Hint=Here you can set which file to execute before the shutdown
logCB_Hint=Logs the shutdowns
annCB_Hint=Visual and acoustic countdown 9 seconds before shutdown
Save4_2_Hint=Save
server_CB_Hint=You can turn off your PC via LAN or Internet
Veszhelyzet_Hint=You can set the hotkeys here, or shutdown your computer fast
SpeedButton1_Hint=Execute
PowerOff_Hint=Shuts down Windows so that you can safely turn off the computer.
ReBoot_Hint=Shuts down Windows and then starts Windows again.
LogOff_Hint=Closes your programs and ends your Windows session.
Hibernate_Hint=Saves your current desktop state to your hard disk so that you can resume where you left off, then shuts down your computer.
HotKeyPOff_Hint=Power Off
HotKeySD_Hint=Shutdown
HotKeyReB_Hint=Restart
HotKeyLO_Hint=Log Off
HotKeyHib_Hint=Hibernate
Save4_Hint=Save
LockWS_Hint=Locks the Workstation
HotKeyLWS_Hint=Lock Workstation
SDMenu_Hint=Show Windows' Shutdown Menu
SSOn_Hint=Launches the Screensaver
HotKeySS_Hint=Screensaver
BitBtn1_Hint=Play sound
HotKeyAA_Hint=Alarm
eject_Hint=Eject CD
close_Hint=Close tray
recbin_Hint=Empty Recycle Bin
clipb_Hint=Clear Clipboard
HotKey1_Hint=Eject CD
HotKey2_Hint=Close tray
HotKey3_Hint=Empty Recycle Bin
HotKey4_Hint=Clear Clipboard
mon0_Hint=Turn monitor off
mon1_Hint=Turn monitor on
hkmon0_Hint=Monitor off
hkmon1_Hint=Monitor on
BitBtn2_Hint=Clear Temporary Internet Files
hkctif_Hint=Clear Temporary Internet Files
Suspend_Hint=Puts your computer in a low-power state so that you can quickly resume your Windows session.
HotKeySus_Hint=Stand By
UserSpecific_Hint=If the current user logs off, don't let him/her log in again for a while
UserCB_Hint=If the current user logs off, don't let him/her log in again for a while
FromTime_Hint=Start time
ToTime_Hint=End time
atom_do_Hint=Synchronize time
TrayIcon_Hint=Shutdown Monster
eleres_Filter=All files (*.*)|*.*|Executables (*.bat; *.com; *.exe)|*.bat;*.com;*.exe
wavE_Filter=Sounds (*.wav)|*.wav|All files (*.*)|*.*
beshutE_Filter=Executables (*.bat; *.com; *.exe)|*.bat;*.com;*.exe|All files (*.*)|*.*
ShutDown_B_Caption=&Shutdown
ShutDown_B_Hint=Shuts down the computer
Kikapcsols1_Caption=&Power Off
N15percmlva1_Caption=After &15 minutes
N30percmlva1_Caption=After &30 minutes
N60percmlva1_Caption=After &60 minutes
N120percmlva1_Caption=After 1&20 minutes
Most1_Caption=&Now
jraindts1_Caption=&Restart
Kijelentkezs1_Caption=&Log Off
Munkallomszrolsa1_Caption=Lock &Workstation
Kpernyvd1_Caption=Scree&nsaver
Mgsem1_Caption=&Cancel
Kilps1_Caption=&Exit
Delet1_Caption=Delete
Kapcs_Caption=Connection
Disconnect_Caption=Disconnect
Connect_Caption=Connect
IP_Edit_Hint=Type in the client's IP address!
langCB_Hint=You can set the default language here
TabSheet1_Caption=CPU usage
Label1_Caption=Current CPU usage is
CPU_L_Caption=100%
If_below_Caption=Execute default command if CPU usage stays below
If_stays_Caption=% for
If_then_Caption=minutes
CPU_SE_Hint=%
Canc4_Caption=Cancel
Canc4_Hint=Stop
Set4_Caption=Set
Set4_Hint=Activate
SaveHK_Hint=Save
