[TShutdown]
Shutdown_FontName=MS Sans Serif
Shutdown_FontSize=8
Shutdown_FontCharset=1
suiForm1_Caption=Shutdown Monster
Time_Caption=Idõpont
Set1_Caption=Beállítás
Canc1_Caption=Mégsem
Button2_Caption=This ain't here
CountDown_Caption=Visszaszámlálás
Set2_Caption=Beállítás
Canc2_Caption=Mégsem
IPing_Caption=Fájl alapján
infoPing_Caption=Ha ez a fájl eltûnik, akkor a számítógép kikapcsol.
infoCheck_Caption=Ellenõrzés
Set3_Caption=Beállítás
Canc3_Caption=Mégsem
AltOptions_Caption=Egyéb
GB_Design_Caption=Kinézet
auto_Caption=Minden nap
parentalcontrol_Caption=Szülõi felügyelet
aftertime_Caption=Idõpont után is (nagyon durva!)
auto2_Caption=Automatikus indítás
minimCB_Caption=Lekicsinyítve indul
ontopCB_Caption=Mindig legfelül
GB_Shutdown_Caption=Leállítás
force_Caption=Alkalmazások kényszerû bezárása
defcommand_Items[0]=Kikapcsolás
defcommand_Items[1]=Leállítás
defcommand_Items[2]=Újraindítás
defcommand_Items[3]=Kijelentkezés
defcommand_Items[4]=Készenlét
defcommand_Items[5]=Hibernálás
defcommand_Items[6]=Munkaállomás lezárása
defcommand_Items[7]=Képernyõkímélõ
defcommand_Items[8]=Riasztás
defcommand_Items[9]=Lemez kiadása
defcommand_Items[10]=Tálca visszahúzása
defcommand_Items[11]=Lomtár ürítése
defcommand_Items[12]=Vágólap ürítése
defcommand_Items[13]=Monitor ki
defcommand_Items[14]=Monitor be
defcommand_Items[15]=Ideiglenesen tárolt fájlok törlése
wake_CB_Caption=Felélesztések letiltása
GB_Alarm_Caption=Riasztás
GB_Before_Caption=Kikapcsolás elõtt végrehajtandó
beshutCB_Caption=Program indítása kikapcsolás elõtt
logCB_Caption=Loggolás
annCB_Caption=Visszaszámlálás kikapcsolás elõtt
GB_Other_Caption=Egyéb
server_CB_Caption=Szerver üzemmód engedélyezése
Button1_Caption=Frissítések keresése
Veszhelyzet_Caption=Gyors elérés
PowerOff_Caption=&Kikapcsolás
ReBoot_Caption=&Újraindítás
LogOff_Caption=K&ijelentkezés
ShutDown_Caption=&Leállítás
Hibernate_Caption=&Hibernálás
LockWS_Caption=&Zárolás
SDMenu_Caption=Kikapcsolás &menü
SSOn_Caption=Képernyõ&védõ
BitBtn1_Caption=&Riasztás
eject_Caption=Lemez kiadása
close_Caption=Tálca visszahúzása
recbin_Caption=Lomtár ürítése
clipb_Caption=Vágólap ürítése
mon0_Caption=Monitor ki
mon1_Caption=Monitor be
BitBtn2_Caption=Ideiglenesen tárolt fájlok törlése
Suspend_Caption=Készenlét
UserSpecific_Caption=Felhasználó specifikus
UserCB_Caption=Engedélyezés
TabSheet2_Caption=Atomóra
atom_label_Caption=A rendszeridõ nincs szinkronizálva
atom_do_Caption=Szinkronizálás
atom_CB_Caption=Ellenõrzés programindításkor
Shutdown_Hint=Shutdown Monster
Valasztas_Hint=Válassz ki egy fület!
Time_Hint=Itt megadható egy konkrét dátum és idõpont
logo_Hint=Névjegy megtekintése
Set1_Hint=A beállítások érvénybe hozatala
Canc1_Hint=A leállítás megállítása
Save1_Hint=Beállítások mentése
Calendar_Hint=Itt adható meg a dátum
Idopont_Hint=Itt adható meg a konkrét idõpont
CountDown_Hint=Itt beállítható a visszaszámlálás
Most_Hint=Itt mutatja, hogy a megadott idõnek hány %-a telt le
Set2_Hint=A beállítások érvénybe hozatala
Canc2_Hint=A leállítás megállítása
Save2_Hint=Beállítások mentése
CD1_Hint=Óra
CD2_Hint=Perc
CD3_Hint=Másodperc
IPing_Hint=Itt megadható egy ellenõrízendõ fájl
infoPing_Hint=Ha ez a fájl eltûnik, akkor a számítógép kikapcsol
infoCheck_Hint=Ellenõrzés minden megadott percben
PingTime_Hint=Itt adható meg, hogy hány percenként ellenõrizze a fájl jelenlétét
Set3_Hint=A beállítások érvénybe hozatala
Save3_Hint=Beállítások mentése
Canc3_Hint=A leállítás megállítása
eleres_Hint=Itt adható meg az ellenõrízendõ fájl nevét. Ajánlatos kis méretû fájlt megadni!
AltOptions_Hint=Itt egyéb, a program mûködését befolyásoló opciók adhatók meg
auto_Hint=A számítógép minden nap kikapcsol a megadott idõpontban vagy a megadott idõ letelte után
parentalcontrol_Hint=A programból csak Ctrl+Alt+Del-el lehet kilépni ('Néma Mód')
aftertime_Hint=Ha a megadott idõpont után bekapcsoljuk a gépet, az rögtön kikapcsol
spintime_Hint=Itt adható meg, hogy hány másodpercet várjon leállítás elõtt
auto2_Hint=A program minden bekapcsoláskor elindul, de nem kapcsol ki automatikusan
minimCB_Hint=A program induláskor lekicsinyíti magát
force_Hint=A programokat mindenképpen bezárja, akkor is ha nincsenek mentve a dokumentumok
defcommand_Hint=Itt adható meg az alapértelmezett parancs
wake_CB_Hint=Az összes felélesztési esemény letiltása (Készenlét és Hibernálás)
wavE_Hint=Itt adható meg, hogy melyik hangot játsza le riasztáskor
wavSE_Hint=Itt adható meg, hogy hányszor játsza le a hangot riasztáskor
beshutCB_Hint=Program indítása kikapcsolás elõtt
beshutE_Hint=Itt adható meg, hogy melyik fájlt indítsa el a kikapcsolás elõtt
logCB_Hint=Feljegyzi, hogy ki, mikor és hogyan kapcsolta ki a számítógépet
annCB_Hint=Vizuális és akusztikus visszaszámlálás a kikapcsolás elõtt 9 másodperccel
Save4_2_Hint=Egyéb beállítások mentése
server_CB_Hint=A számítógépedet LAN-on és Interneten keresztül is kikapcsolhatod
Veszhelyzet_Hint=Itt billentyûparancsok adhatók meg, valamint gyorsan ki lehet lépni a Windowsból
SpeedButton1_Hint=Végrehajtás
PowerOff_Hint=Kikapcsolja a gépet, ha az ATX elérhetõ
ReBoot_Hint=Újraindítja a számítógépet
LogOff_Hint=Kijelentkezik a Windows-ból
Hibernate_Hint=Lefagyassza a számítógépet
HotKeyPOff_Hint=Kikapcsolás
HotKeySD_Hint=Leállítás
HotKeyReB_Hint=Újraindítás
HotKeyLO_Hint=Kijelentkezés
HotKeyHib_Hint=Hibernálás
Save4_Hint=Beállítások mentése
LockWS_Hint=Lezárja a munkaállomást
HotKeyLWS_Hint=Munkaállomás zárolása
SDMenu_Hint=Megjeleníti a Windows Kikapcsolás menüjét
SSOn_Hint=Elindítja a képernyõkímélõt
HotKeySS_Hint=Képernyõkímélõ indítása
BitBtn1_Hint=Hang lejátszása
HotKeyAA_Hint=Riasztás
eject_Hint=Tálca kinyitása
close_Hint=Tálca visszahúzása
recbin_Hint=Lomtár ürítése
clipb_Hint=Vágólap ürítése
HotKey1_Hint=Lemez kiadása
HotKey2_Hint=Tálca visszahúzása
HotKey3_Hint=Lomtár ürítése
HotKey4_Hint=Vágólap ürítése
mon0_Hint=Monitor kikapcsolása
mon1_Hint=Monitor bekapcsolása
hkmon0_Hint=Monitor ki
hkmon1_Hint=Monitor be
BitBtn2_Hint=Az ideiglenesen tárolt fájlok letörlése
hkctif_Hint=Ideiglenesen tárolt fájlok törlése
Suspend_Hint=Készenlét
HotKeySus_Hint=Készenlét
UserSpecific_Hint=Ha a jelenlegi felhasználó kilép, akkor nem engedi belépni egy ideig
UserCB_Hint=Ha a jelenlegi felhasználó kilép, akkor nem engedi belépni egy ideig
FromTime_Hint=Itt adható meg a kezdeti idõpont
ToTime_Hint=Itt adható meg a befejezési idõpont
atom_do_Hint=Idõ szinkronizálása
TrayIcon_Hint=Shutdown Monster
eleres_Filter=Minden fájl (*.*)|*.*|Fontosabb fájlok (*.bat; *.com; *.exe)|*.bat;*.com;*.exe
wavE_Filter=Hangok (*.wav)|*.wav|Minden fájl (*.*)|*.*
beshutE_Filter=Fontosabb fájlok (*.bat; *.com; *.exe)|*.bat;*.com;*.exe|Minden fájl (*.*)|*.*
ShutDown_B_Caption=&Leállítás
ShutDown_B_Hint=Leállítja a gépet (Most már kikapcsolhatja a számítógépet)
Kikapcsols1_Caption=&Kikapcsolás
N15percmlva1_Caption=&15 perc múlva
N30percmlva1_Caption=&30 perc múlva
N60percmlva1_Caption=&60 perc múlva
N120percmlva1_Caption=1&20 perc múlva
Most1_Caption=&Most
jraindts1_Caption=&Újraindítás
Kijelentkezs1_Caption=K&ijelentkezés
Munkallomszrolsa1_Caption=Munkaállomás &zárolása
Kpernyvd1_Caption=Képernyõ&védõ
Mgsem1_Caption=&Mégsem
Kilps1_Caption=Kilépés
Delet1_Caption=Törlés
TabSheet1_Caption=CPU használtság
Label1_Caption=Jelenlegi CPU használtság:
CPU_L_Caption=100%
If_below_Caption=Alapértelmezett parancs végrehajtása, ha a CPU használtsága
If_stays_Caption=% alatt marad
If_then_Caption=percen keresztül
CPU_SE_Hint=%
Canc4_Caption=Mégsem
Canc4_Hint=A leállítás megállítása
Set4_Caption=Beállítás
Set4_Hint=A beállítások érvénybe hozatala
SaveHK_Hint=Gyorsbillentyûk mentése
Hook_CB_Caption=Kikapcsolás csak akkor, ha nincs adatbevitel
Kapcs_Caption=Kapcsolat
Disconnect_Caption=Leválasztás
Connect_Caption=Csatlakozás
volfade_CB_Caption=Hangerõ lehalkítása kikapcsolás elõtt
Label1_Hint=A jelenlegi processzor kihasználtságát mutatja
CPUMin_SE_Hint=Perc
Hook_CB_Hint=Kikapcsolás csak akkor, ha nem mozog az egér és nem írunk a billentyûzeten
ontopCB_Hint=Ezt az ablakot nem takarja el másik ablak
volfade_CB_Hint=A hangerõ lassú lehúzása kikapcsolás elõtt
volfade_E_Hint=A lehalkítás sebessége
Button1_Hint=Új verzió keresése
atom_add_Hint=Szerver hozzáadása
